# Generated by Django 5.1.2 on 2024-10-17 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='строковое поле для имени автора.')),
                ('birthdate', models.DateField(verbose_name='поле даты для дня рождения автора.')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name=' строковое поле для названия книги')),
                ('publication_year', models.DateTimeField(verbose_name='целочисленное поле для года издания.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.author')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'книжки',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name=' строковое поле для названия жанра')),
                ('books', models.ManyToManyField(related_name='genre_book', to='base.book')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'жанры',
            },
        ),
    ]
